/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CellApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CellApi'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiDocumentation) {
      root.ApiDocumentation = {};
    }
    root.ApiDocumentation.BoardApi = factory(root.ApiDocumentation.ApiClient, root.ApiDocumentation.CellApi);
  }
}(this, function(ApiClient, CellApi) {
  'use strict';




  /**
   * The BoardApi model module.
   * @module model/BoardApi
   * @version 1.0
   */

  /**
   * Constructs a new <code>BoardApi</code>.
   * @alias module:model/BoardApi
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>BoardApi</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BoardApi} obj Optional instance to populate.
   * @return {module:model/BoardApi} The populated <code>BoardApi</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('cells')) {
        obj['cells'] = ApiClient.convertToType(data['cells'], [CellApi]);
      }
      if (data.hasOwnProperty('gameId')) {
        obj['gameId'] = ApiClient.convertToType(data['gameId'], 'Number');
      }
      if (data.hasOwnProperty('playerName')) {
        obj['playerName'] = ApiClient.convertToType(data['playerName'], 'String');
      }
    }
    return obj;
  }

  /**
   * The list of cells for the game
   * @member {Array.<module:model/CellApi>} cells
   */
  exports.prototype['cells'] = undefined;
  /**
   * The game ID, this is unique
   * @member {Number} gameId
   */
  exports.prototype['gameId'] = undefined;
  /**
   * The player name
   * @member {String} playerName
   */
  exports.prototype['playerName'] = undefined;



  return exports;
}));


